### ISSUE TITLE
User model creation and migration to DB

### ISSUE THREAD

**Issue by KamilFilip** [Ragnarson-Internship2016/group-III#4]
Since we need user to authenticate data, we have to generate User model via devise. Table Users should have following attributes
name :string
surname :string
email :string
city :string
Validations: We should validate presence and content type of above attributes.
Relations:  User should have many events

**Comment by trueskawka** [comment]
> User should have many games.

1. It was not a part of critical functionalities - games are assigned to events.
2. If it were to be assigned to the user, the model is missing FK from game.

**Comment by hav3loc** [comment]
If user can have many events, shouldn't model event include user FK instead?
